import re


MILITARY_ENTRIES = (
    # Commonwealth, British Empire, Dominion, and AIF war-diary forms.
    (r"\b(?:Lt[\s.-]*Col|Lieut[\s.-]*Col)\b\.?", "Lieutenant Colonel"),
    (r"\b(?:Maj[\s.-]*Gen|Major[\s.-]*Gen)\b\.?", "Major General"),
    (r"\b(?:Brig[\s.-]*Gen|Brigadier[\s.-]*Gen)\b\.?", "Brigadier General"),
    (r"\b(?:2/Lt|2nd[\s.-]*Lt|Second[\s.-]*Lt)\b\.?", "Second Lieutenant"),
    (r"\b(?:1/Lt|1st[\s.-]*Lt|First[\s.-]*Lt)\b\.?", "First Lieutenant"),
    (r"\b(?:L/Sgt|Lce[\s.-]*Sgt)\b\.?", "Lance Sergeant"),
    (r"\b(?:L/Cpl|Lce[\s.-]*Cpl)\b\.?", "Lance Corporal"),
    (r"\b(?:Actg|A/)\s*(?=(?:Cpl|Sgt|Capt|Maj|Lt|Lieut|Col|WO|RSM|CSM)\b)", "Acting "),
    (r"\b(?:Coy|Co)\b\.?", "Company"),
    (r"\b(?:Bn|Battn)\b\.?", "Battalion"),
    (r"\b(?:Regt|Regt\.|Rgt)\b\.?", "Regiment"),
    (r"\bBde\b\.?", "Brigade"),
    (r"\bDiv\b\.?", "Division"),
    (r"\b(?:Pltn|Platoon)\b\.?", "Platoon"),
    (r"\b(?:Sect|Sec)\b\.?", "Section"),
    (r"\bDet\b\.?", "Detachment"),
    (r"\bSqn\b\.?", "Squadron"),
    (r"\b(?:Bty|Btry)\b\.?", "Battery"),
    (r"\bHQ\b\.?", "Headquarters", 0),
    (r"\bG\.?H\.?Q\b\.?", "General Headquarters", 0),
    (r"\bB\.?Ech\b\.?", "B Echelon"),
    (r"\bF\.?Ech\b\.?", "F Echelon"),
    (r"\bAdjt\b\.?", "Adjutant"),
    (r"\b(?:Lieut|Lt)\b\.?", "Lieutenant"),
    (r"\bCapt\b\.?", "Captain"),
    (r"\bMaj\b\.?", "Major"),
    (r"\bCol\b\.?", "Colonel"),
    (r"\bBrig\b\.?", "Brigadier"),
    (r"\bGen\b\.?", "General"),
    (r"\b(?:Sgt|Sergt)\b\.?", "Sergeant"),
    (r"\bCpl\b\.?", "Corporal"),
    (r"\bPte\b\.?", "Private"),
    (r"\bGnr\b\.?", "Gunner"),
    (r"\bDvr\b\.?", "Driver"),
    (r"\bSpr\b\.?", "Sapper"),
    (r"\bTpr\b\.?", "Trooper"),
    (r"\bSig\b\.?", "Signaller"),
    (r"\bBdr\b\.?", "Bombardier"),
    (r"\bNCOs\b\.?", "Non-Commissioned Officers"),
    (r"\bNCO\b\.?", "Non-Commissioned Officer"),
    (r"\bW\.?O\b\.?", "Warrant Officer", 0),
    (r"\bR\.?S\.?M\b\.?", "Regimental Sergeant Major", 0),
    (r"\bC\.?S\.?M\b\.?", "Company Sergeant Major", 0),
    (r"\bB\.?S\.?M\b\.?", "Battery Sergeant Major", 0),
    (r"\bR\.?Q\.?M\.?S\b\.?", "Regimental Quartermaster Sergeant", 0),
    (r"\bC\.?Q\.?M\.?S\b\.?", "Company Quartermaster Sergeant", 0),
    (r"\bO\.?R\.?s\b\.?", "Other Ranks", 0),
    (r"\bO\.?C\b\.?", "Officer Commanding", 0),
    (r"\bC\.?O\b\.?", "Commanding Officer", 0),
    (r"\bG\.?O\.?C\b\.?", "General Officer Commanding", 0),
    (r"\bA\.?D\.?C\b\.?", "Aide-de-Camp", 0),
    (r"\bQ\.?M\b\.?", "Quartermaster", 0),
    (r"\bT\.?O\.?S\b\.?", "Taken on Strength", 0),
    (r"\bS\.?O\.?S\b\.?", "Struck off Strength", 0),
    (r"\bR\.?T\.?U\b\.?", "Returned to Unit", 0),
    (r"\bA\.?W\.?O\.?L\b\.?", "Absent Without Leave", 0),
    (r"\bA\.?W\.?L\b\.?", "Absent Without Leave", 0),
    (r"\bD\.?O\.?W\b\.?", "Died of Wounds", 0),
    (r"\bK\.?I\.?A\b\.?", "Killed in Action", 0),
    (r"\bW\.?I\.?A\b\.?", "Wounded in Action", 0),
    (r"\bM\.?I\.?A\b\.?", "Missing in Action", 0),
    (r"\bP\.?O\.?W\b\.?", "Prisoner of War", 0),
    (r"\bA\.?I\.?F\b\.?", "Australian Imperial Force", 0),
    (r"\bB\.?E\.?F\b\.?", "British Expeditionary Force", 0),
    (r"\bC\.?E\.?F\b\.?", "Canadian Expeditionary Force", 0),
    (r"\bN\.?Z\.?E\.?F\b\.?", "New Zealand Expeditionary Force", 0),
    (r"\bA\.?E\.?F\b\.?", "American Expeditionary Forces", 0),
    (r"\bA\.?N\.?Z\.?A\.?C\b\.?", "Australian and New Zealand Army Corps", 0),
    (r"\bC\.?M\.?F\b\.?", "Citizen Military Forces", 0),
    (r"\bR\.?A\.?A\b\.?", "Royal Australian Artillery", 0),
    (r"\bR\.?A\.?E\b\.?", "Royal Australian Engineers", 0),
    (r"\bA\.?A\.?M\.?C\b\.?", "Australian Army Medical Corps", 0),
    (r"\bA\.?A\.?S\.?C\b\.?", "Australian Army Service Corps", 0),
    (r"\bR\.?A\.?M\.?C\b\.?", "Royal Army Medical Corps", 0),
    (r"\bR\.?A\.?S\.?C\b\.?", "Royal Army Service Corps", 0),
    (r"\bR\.?A\.?O\.?C\b\.?", "Royal Army Ordnance Corps", 0),
    (r"\bR\.?E\b\.?", "Royal Engineers", 0),
    (r"\bR\.?A\b\.?", "Royal Artillery", 0),
    (r"\bR\.?H\.?A\b\.?", "Royal Horse Artillery", 0),
    (r"\bR\.?F\.?A\b\.?", "Royal Field Artillery", 0),
    (r"\bR\.?G\.?A\b\.?", "Royal Garrison Artillery", 0),
    (r"\bM\.?G\.?C\b\.?", "Machine Gun Corps", 0),
    (r"\bT\.?M\.?B\b\.?", "Trench Mortar Battery", 0),
    (r"\bArty\b\.?", "Artillery"),
    (r"\bCav\b\.?", "Cavalry"),
    (r"\bInf\b\.?", "Infantry"),
    (r"\bEngrs\b\.?", "Engineers"),
    (r"\b(?:Fd\s*Amb|F\.?A)\b\.?", "Field Ambulance"),
    (r"\bR\.?A\.?P\b\.?", "Regimental Aid Post", 0),
    (r"\bA\.?D\.?S\b\.?", "Advanced Dressing Station", 0),
    (r"\bM\.?D\.?S\b\.?", "Main Dressing Station", 0),
    (r"\bC\.?C\.?S\b\.?", "Casualty Clearing Station", 0),
    (r"\bM\.?O\b\.?", "Medical Officer", 0),
    (r"\bR\.?M\.?O\b\.?", "Regimental Medical Officer", 0),
    (r"\bD\.?A\.?D\.?M\.?S\b\.?", "Deputy Assistant Director of Medical Services", 0),
    (r"\bA\.?D\.?M\.?S\b\.?", "Assistant Director of Medical Services", 0),
    (r"\bD\.?D\.?M\.?S\b\.?", "Deputy Director of Medical Services", 0),
    # US Army, Marine Corps, Navy, Coast Guard, and WWII operational abbreviations.
    (r"\bU\.?S\.?A\.?A\.?F\b\.?", "United States Army Air Forces", 0),
    (r"\bU\.?S\.?A\.?F\.?F\.?E\b\.?", "United States Army Forces in the Far East", 0),
    (r"\bU\.?S\.?M\.?C\b\.?", "United States Marine Corps", 0),
    (r"\bU\.?S\.?N\b\.?", "United States Navy", 0),
    (r"\bU\.?S\.?C\.?G\b\.?", "United States Coast Guard", 0),
    (r"\bU\.?S\.?S\b\.?", "United States Ship", 0),
    (r"\bA\.?A\.?F\b\.?", "Army Air Forces", 0),
    (r"\bA\.?A\.?A\b\.?", "Antiaircraft Artillery", 0),
    (r"\bA\.?A\b\.?", "Antiaircraft", 0),
    (r"\bA\.?F\.?V\b\.?", "Armored Fighting Vehicle", 0),
    (r"\bA\.?S\.?W\b\.?", "Antisubmarine Warfare", 0),
    (r"\bC\.?A\.?P\b\.?", "Combat Air Patrol", 0),
    (r"\bC\.?I\.?C\b\.?", "Combat Information Center", 0),
    (r"\bC\.?P\b\.?", "Command Post", 0),
    (r"\bM\.?P\b\.?", "Military Police", 0),
    (r"\bX\.?O\b\.?", "Executive Officer", 0),
    (r"\bC\.?G\b\.?", "Commanding General", 0),
    (r"\bC\.?I\.?N\.?C\b\.?", "Commander in Chief", 0),
    (r"\bC\.?O\.?S\b\.?", "Chief of Staff", 0),
    (r"\bE\.?T\.?O\b\.?", "European Theater of Operations", 0),
    (r"\bM\.?T\.?O\b\.?", "Mediterranean Theater of Operations", 0),
    (r"\bP\.?T\.?O\b\.?", "Pacific Theater of Operations", 0),
    (r"\bS\.?W\.?P\.?A\b\.?", "Southwest Pacific Area", 0),
    (r"\bC\.?B\.?I\b\.?", "China-Burma-India Theater", 0),
    (r"\bB\.?A\.?R\b\.?", "Browning Automatic Rifle", 0),
    (r"\bL\.?S\.?T\b\.?", "Landing Ship, Tank", 0),
    (r"\bL\.?C\.?I\b\.?", "Landing Craft, Infantry", 0),
    (r"\bL\.?C\.?T\b\.?", "Landing Craft, Tank", 0),
    (r"\bL\.?C\.?M\b\.?", "Landing Craft, Mechanized", 0),
    (r"\bL\.?V\.?T\b\.?", "Landing Vehicle, Tracked", 0),
    (r"\bU\.?D\.?T\b\.?", "Underwater Demolition Team", 0),
    (r"\bPfc\b\.?", "Private First Class"),
    (r"\bPvt\b\.?", "Private"),
    (r"\b(?:T/Sgt|TSgt)\b\.?", "Technical Sergeant"),
    (r"\b(?:S/Sgt|SSgt)\b\.?", "Staff Sergeant"),
    # Naval and air forces across Commonwealth and Allied records.
    (r"\bH\.?M\.?A\.?S\b\.?", "His Majesty's Australian Ship", 0),
    (r"\bH\.?M\.?N\.?Z\.?S\b\.?", "His Majesty's New Zealand Ship", 0),
    (r"\bH\.?M\.?S\b\.?", "His Majesty's Ship", 0),
    (r"\bR\.?A\.?A\.?F\b\.?", "Royal Australian Air Force", 0),
    (r"\bR\.?N\.?Z\.?A\.?F\b\.?", "Royal New Zealand Air Force", 0),
    (r"\bR\.?A\.?F\b\.?", "Royal Air Force", 0),
    (r"\bR\.?F\.?C\b\.?", "Royal Flying Corps", 0),
    (r"\bR\.?N\.?A\.?S\b\.?", "Royal Naval Air Service", 0),
    (r"\bR\.?A\.?N\b\.?", "Royal Australian Navy", 0),
    (r"\bR\.?N\b\.?", "Royal Navy", 0),
    (r"\bF\.?A\.?A\b\.?", "Fleet Air Arm", 0),
    (r"\bI\.?J\.?A\b\.?", "Imperial Japanese Army", 0),
    (r"\bI\.?J\.?N\b\.?", "Imperial Japanese Navy", 0),
    (r"\bI\.?G\.?H\.?Q\b\.?", "Imperial General Headquarters", 0),
    # German records and translated German unit/rank shorthand.
    (r"\bO\.?K\.?W\b\.?", "Oberkommando der Wehrmacht", 0),
    (r"\bO\.?K\.?H\b\.?", "Oberkommando des Heeres", 0),
    (r"\bO\.?K\.?L\b\.?", "Oberkommando der Luftwaffe", 0),
    (r"\bHGr\b\.?", "Heeresgruppe"),
    (r"\bA\.?O\.?K\b\.?", "Armeeoberkommando"),
    (r"\bAbt\b\.?", "Abteilung"),
    (r"\b(?:Kp|Komp)\b\.?", "Kompanie"),
    (r"\b(?:Batl|Btl)\b\.?", "Bataillon"),
    (r"\bPz\.?\s*Gren\b\.?", "Panzergrenadier"),
    (r"\bPz\b\.?", "Panzer"),
    (r"\bStuG\b\.?", "Sturmgeschütz"),
    (r"\bFlak\b\.?", "Flugabwehrkanone"),
    (r"\bPak\b\.?", "Panzerabwehrkanone"),
    (r"\bJg\b\.?", "Jäger"),
    (r"\bUffz\b\.?", "Unteroffizier"),
    (r"\bGefr\b\.?", "Gefreiter"),
    (r"\bOgefr\b\.?", "Obergefreiter"),
    (r"\bFeldw\b\.?", "Feldwebel"),
    (r"\bHptm\b\.?", "Hauptmann"),
    (r"\bOblt\b\.?", "Oberleutnant"),
    (r"\bObstlt\b\.?", "Oberstleutnant"),
    (r"\bObst\b\.?", "Oberst"),
    (r"\bGenMaj\b\.?", "Generalmajor"),
    (r"\bGenLt\b\.?", "Generalleutnant"),
    (r"\bOHL\b\.?", "Oberste Heeresleitung"),
    (r"\bArtl\b\.?", "Artillerie"),
    # French and Belgian records.
    (r"\bG\.?Q\.?G\b\.?", "Grand Quartier Général", 0),
    (r"\bQ\.?G\b\.?", "Quartier Général", 0),
    (r"\b(?:Régt|Rgt)\b\.?", "Régiment"),
    (r"\bR\.?I\b\.?", "Régiment d'Infanterie", 0),
    (r"\bR\.?I\.?C\b\.?", "Régiment d'Infanterie Coloniale", 0),
    (r"\bCie\b\.?", "Compagnie"),
    (r"\b(?:Bat|Btn)\b\.?", "Bataillon"),
    (r"\bAdj\b\.?", "Adjudant"),
    (r"\bCne\b\.?", "Capitaine"),
    (r"\b(?:Cdt|Cmdt)\b\.?", "Commandant"),
    (r"\bGén\b\.?", "Général"),
    (r"\bSdt\b\.?", "Soldat"),
    # Italian, Russian/Soviet, and other common coalition identifiers.
    (r"\bR\.?Esercito\b\.?", "Regio Esercito"),
    (r"\bM\.?S\.?V\.?N\b\.?", "Milizia Volontaria per la Sicurezza Nazionale", 0),
    (r"\bR\.?K\.?K\.?A\b\.?", "Workers' and Peasants' Red Army", 0),
    (r"\bN\.?K\.?V\.?D\b\.?", "People's Commissariat for Internal Affairs", 0),
    (r"\bA\.?E\.?F\.?F\.?I\b\.?", "Allied Expeditionary Force, France and Flanders", 0),
)
