import re


HISTORICAL_NEWSPAPER_ENTRIES = (
    # Dates, notices, classifieds, and older newspaper shorthand.
    (r"\binst\b\.?", "this month"),
    (r"\bult\b\.?", "last month"),
    (r"\bprox\b\.?", "next month"),
    (r"\bNo\b\.?(?=\s*\d)", "Number"),
    (r"\bacct\b\.?", "account"),
    (r"\bbal\b\.?", "balance"),
    (r"\bdoz\b\.?", "dozen"),
    (r"\bcwt\b\.?", "hundredweight"),
    (r"\bqr\b\.?", "quarter"),
    (r"\blb\b\.?", "pound"),
    (r"\boz\b\.?", "ounce"),
    (r"\bgent\b\.?", "gentleman"),
    (r"\bfurn\b\.?", "furnished"),
    (r"\bunfurn\b\.?", "unfurnished"),
    (r"\brefs\b\.?", "references"),
    (r"\bimmed\b\.?", "immediately"),
    (r"\bbd\b\.?", "board"),
    (r"\blodg\b\.?", "lodging"),
    (r"\bdom\.?\s*servt\b\.?", "domestic servant"),
    # Shipping and transport columns.
    (r"\bS\.?S\b\.?", "Steamship", 0),
    (r"\bR\.?M\.?S\b\.?", "Royal Mail Ship", 0),
    (r"\bstr\b\.?", "steamer"),
    (r"\bschr\b\.?", "schooner"),
    (r"\bbk\b\.?", "barque"),
    (r"\barr\b\.?", "arrived"),
    (r"\bdep\b\.?", "departed"),
    (r"\btons\s+reg\b\.?", "tons registered"),
    # Places and civic geography often printed in compressed address lines.
    (r"\bRd\b\.?", "Road"),
    (r"\bAve\b\.?", "Avenue"),
    (r"\bMt\b\.?", "Mount"),
    (r"\bFt\b\.?", "Fort"),
    (r"\bN\.?S\.?W\b\.?", "New South Wales", 0),
    (r"\bQld\b\.?", "Queensland"),
    (r"\bVic\b\.?", "Victoria"),
    (r"\bTas\b\.?", "Tasmania"),
    (r"\bS\.?A\b\.?", "South Australia", 0),
    (r"\bW\.?A\b\.?", "Western Australia", 0),
    (r"\bN\.?Z\b\.?", "New Zealand", 0),
    (r"\bU\.?K\b\.?", "United Kingdom", 0),
    (r"\bU\.?S\b\.?", "United States", 0),
)

MODERN_NEWSPAPER_ENTRIES = (
    # Wire services and contemporary public-language abbreviations.
    (r"\bA\.?P\b\.?", "Associated Press", 0),
    (r"\bA\.?A\.?P\b\.?", "Australian Associated Press", 0),
    (r"\bA\.?F\.?P\b\.?", "Agence France-Presse", 0),
    (r"\bP\.?A\b\.?", "Press Association", 0),
    (r"\bD\.?P\.?A\b\.?", "Deutsche Presse-Agentur", 0),
    (r"\bE\.?F\.?E\b\.?", "Agencia EFE", 0),
    (r"\bA\.?N\.?S\.?A\b\.?", "Agenzia Nazionale Stampa Associata", 0),
    (r"\bTASS\b", "Russian News Agency TASS", 0),
    (r"\bN\.?Z\.?P\.?A\b\.?", "New Zealand Press Association", 0),
    (r"\bC\.?P\b\.?", "The Canadian Press", 0),
    # Politics, economy, technology, courts, and health in modern news.
    (r"\bU\.?N\b\.?", "United Nations", 0),
    (r"\bE\.?U\b\.?", "European Union", 0),
    (r"\bNATO\b", "North Atlantic Treaty Organization", 0),
    (r"\bW\.?H\.?O\b\.?", "World Health Organization", 0),
    (r"\bI\.?M\.?F\b\.?", "International Monetary Fund", 0),
    (r"\bG\.?D\.?P\b\.?", "Gross Domestic Product", 0),
    (r"\bC\.?P\.?I\b\.?", "Consumer Price Index", 0),
    (r"\bI\.?P\.?O\b\.?", "Initial Public Offering", 0),
    (r"\bE\.?T\.?F\b\.?", "Exchange-Traded Fund", 0),
    (r"\bC\.?E\.?O\b\.?", "Chief Executive Officer", 0),
    (r"\bC\.?F\.?O\b\.?", "Chief Financial Officer", 0),
    (r"\bbps\b", "basis points"),
    (r"\bYoY\b", "year over year", 0),
    (r"\bQoQ\b", "quarter over quarter", 0),
    (r"\bD\.?N\.?A\b\.?", "deoxyribonucleic acid", 0),
    (r"\bC\.?C\.?T\.?V\b\.?", "closed-circuit television", 0),
)
