from chronicle_app.services.runtime_policies import DEFAULT_CLAUDE_MODEL

TRANSLATION_TARGETS = [
    ("English", "en"),
    ("Spanish", "es"),
    ("French", "fr"),
    ("German", "de"),
    ("Italian", "it"),
    ("Portuguese", "pt"),
]

RTL_LANGUAGE_CODES = {"ar", "fa", "he", "ur", "yi", "ps", "sd", "ug"}

PROFILE_CHOICES = [
    ("standard", "Miscellaneous / Mixed Files"),
    ("letters", "Letters / Correspondence"),
    ("office", "Reports / Business Files"),
    ("government", "Government Reports / Records"),
    ("legal", "Legal / Contracts / Laws"),
    ("forms", "Forms / Checklists"),
    ("tabular", "Tables / Spreadsheets"),
    ("manual", "Manuals / Procedures"),
    ("slides", "Slides / Presentations"),
    ("flyer", "Flyers / Posters"),
    ("brochure", "Brochures / Catalogues"),
    ("modern_newspaper", "Modern Newspapers / E-Papers"),
    ("magazine", "Magazines / Periodicals"),
    ("comic", "Comics / Manga / Graphic Novels"),
    ("book", "Books / Novels"),
    ("newspaper", "Historical Newspapers"),
    ("academic", "Academic / Research"),
    ("transcript", "Scripts / Dialogue / Transcripts"),
    ("poetry", "Poetry / Verse"),
    ("handwritten", "Handwritten Notes / Personal Diaries"),
    ("archival", "Archives / Historical"),
    ("medical", "Medical Records / Clinical Handwriting"),
    ("military", "Military Records"),
    ("intelligence", "Intelligence / Cables"),
    ("museum", "Museum Labels / Captions"),
]

PROFILE_PRESETS = {
    "standard": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": True,
        "unit_conversion": False,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "office": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": True,
        "unit_conversion": False,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "government": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": True,
        "unit_conversion": False,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "letters": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "archival": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": True,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "handwritten": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "medical": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "military": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": True,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "intelligence": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "newspaper": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": True,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": True,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "modern_newspaper": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": True,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": True,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "book": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": False,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": True,
        "collision_mode": "auto",
    },
    "manual": {
        "model_name": "gemini-2.5-flash",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "forms": {
        "model_name": "gemini-2.5-flash",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "flyer": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": True,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "brochure": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": True,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "magazine": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": True,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "comic": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": True,
        "large_print": False,
        "merge_files": True,
        "collision_mode": "auto",
    },
    "slides": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": True,
        "unit_conversion": False,
        "abbrev_expansion": True,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "tabular": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": False,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "academic": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "transcript": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": True,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": False,
        "preserve_original_page_numbers": True,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "poetry": {
        "model_name": DEFAULT_CLAUDE_MODEL,
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": False,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "legal": {
        "model_name": "gemini-2.5-pro",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": True,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
    "museum": {
        "model_name": "gpt-4o",
        "translate_mode": "none",
        "translate_target": "English",
        "modernize_punctuation": False,
        "unit_conversion": False,
        "abbrev_expansion": False,
        "image_descriptions": True,
        "preserve_original_page_numbers": False,
        "large_print": False,
        "merge_files": False,
        "collision_mode": "auto",
    },
}

PROFILE_LABEL_TO_KEY = {label: key for key, label in PROFILE_CHOICES}
PROFILE_KEY_TO_LABEL = {key: label for key, label in PROFILE_CHOICES}

MODEL_LABEL_BY_KEY = {
    "gemini-2.5-flash": "Gemini 2.5 Flash",
    "gemini-2.5-pro": "Gemini 2.5 Pro",
    DEFAULT_CLAUDE_MODEL: "Claude Sonnet 4",
    "gpt-4o": "GPT-4o",
}

MODEL_OVERRIDE_CHOICES = [
    ("", "Automatic (Chronicle Chooses)"),
    ("gemini-2.5-flash", "Gemini 2.5 Flash"),
    ("gemini-2.5-pro", "Gemini 2.5 Pro"),
    (DEFAULT_CLAUDE_MODEL, "Claude Sonnet 4"),
    ("gpt-4o", "GPT-4o"),
]
